### ISSUE TITLE
Need a better way to recover from a project exists error on OSO Starter

### ISSUE THREAD

**Issue by rdruss** [fabric8-launch/launchpad-frontend#190]
So, I was using Launch to deploy to OpenShift Online Starter and I got this error:

![image](https://user-images.githubusercontent.com/367748/30868991-4c4b2a60-a29d-11e7-8666-1ad9e291132e.png)

So naturally, I went into my OpenShift console and deleted the existing project and then hit "Try Again" and got this message:

![image](https://user-images.githubusercontent.com/367748/30869029-6b5e7d62-a29d-11e7-9532-27f3a9d4561c.png)

Which makes sense since the GitHub repository was created before the deployment to OpenShift.  I'm thinking there either needs to be a warning on the project exists error that states "delete project and github repo and try again" or don't provide the "Try Again" option.  I believe this is an important flow to get right as people trying things out on OpenShift Online Starter would possibly want to try out multiple boosters.

**Comment by edewit** [comment]
I think a good solution would be that if you could retry one step instead of the entire process WDYT?

**Comment by rdruss** [comment]
Yes, limiting the retry to the step that errored out makes more sense to me and actually what I had expected when I clicked on "Try Again"

**Comment by rdruss** [comment]
You may also want a different error message, maybe something that lets the user know what happened without having to dig through that technical error message.  Just a thought.  :-)

**Comment by quintesse** [comment]
Dup of https://github.com/openshiftio/appdev-planning/issues/60, closing this one because it's an issue of several modules, not just the frontend.
