### ISSUE TITLE
Project quota exceeded error message is kind of ugly

### ISSUE THREAD

**Issue by jasonmadigan** [fabric8-launch/launchpad-frontend#209]
Got most of the way through the launch wizard, but I had one project already in my OSO account, so creating another would exceed my quota.

See attached error:

<img width="852" alt="screen shot 2017-11-14 at 11 25 11" src="https://user-images.githubusercontent.com/4467/32780774-59317bbc-c93a-11e7-8648-9f1332074e65.png">

**Comment by ALRubinger** [comment]
Suggested fix: validation ahead of creation to check that no projects already exist on OSO

**Comment by ALRubinger** [comment]
Or, better: check against OpenShift instance quota to see if quota will support adding a new project
