### ISSUE TITLE
appdev.openshift.io - SSL cert expired

### ISSUE THREAD

**Issue by jasonmadigan** [fabric8-launch/launchpad-frontend#211]
<img width="1212" alt="screen shot 2017-11-14 at 11 57 09" src="https://user-images.githubusercontent.com/4467/32780909-e7512212-c93a-11e7-9bb1-f38b53a69c20.png">

**Comment by ALRubinger** [comment]
Moving to appdev-planning; thank you for this, @jasonmadigan!
