### ISSUE TITLE
Trying to associate the Starter cluster in the Account linking screen gives Invalid Request screen in Keycloak

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launch/launchpad-frontend#212]
![screenshot from 2017-11-16 19-08-29](https://user-images.githubusercontent.com/54133/32916001-dd0f207e-cb01-11e7-92a9-9f2dfdd5d9d8.png)

![screenshot from 2017-11-16 19-06-53](https://user-images.githubusercontent.com/54133/32915863-77cd898a-cb01-11e7-9dc4-a80503fc8728.png)

**Comment by edewit** [comment]
To test the "Add" button of this screen you have to take the following steps:
1) log into and remove the cluster from http://sso.openshift.io/auth/realms/rh-developers-launch/account/identity
1) logout
1) open an incognito browser (or clear all cookies) and then use the "Add" button
