### ISSUE TITLE
Decouple adding of a new runtime from launchpad-frontend

### ISSUE THREAD

**Issue by valdar** [fabric8-launch/launchpad-frontend#214]
Ideally should be possible to add a new runtime just by modifying https://github.com/fabric8-launch/booster-catalog.

The only needed pieces here are in https://github.com/fabric8-launch/launchpad-frontend/tree/master/src/assets/img/project-select-icons ?

**Comment by gastaldi** [comment]
This issue was moved to openshiftio/appdev-planning#73
