### ISSUE TITLE
Decouple adding of a new mission from launchpad-frontend

### ISSUE THREAD

**Issue by valdar** [fabric8-launch/launchpad-frontend#215]
Ideally should be possible to add a new mission just by modifying https://github.com/fabric8-launch/booster-catalog.

The only needed pieces here are in https://github.com/fabric8-launch/launchpad-frontend/blob/master/src/assets/adoc.index ?

**Comment by gastaldi** [comment]
This issue was moved to openshiftio/appdev-planning#74
