### ISSUE TITLE
Input validation on artefact Id (aka App Name)

### ISSUE THREAD

**Issue by heiko-braun** [fabric8-launch/launchpad-frontend#99]
The APP_NAME, derived from the maven artefact Id defined in the UI has some constraints, that show up when deploying a project to Openshift:

Invalid value:  must match the regex [a-z]([-a-z0-9]*[a-z0-9])? (e.g. 'my-name' or 'abc-123’)

Is this already covered in the UI through means of input validation?

**Comment by heiko-braun** [comment]
One more thing to consider: IIRC Openshift also has constraints on number of characters. That’s something we need to double check.

**Comment by heiko-braun** [comment]
See also https://github.com/kubernetes/kubernetes/issues/12463 on the service name character limit. Not sure what Kube version is underneath OSO atm, but I assume the limit is still 24 characters.

**Comment by Ladicek** [comment]
It's actually 63 characters since Kube 1.4 / OpenShift 1.4, see https://github.com/kubernetes/kubernetes/pull/29523.

**Comment by heiko-braun** [comment]
Thanks @Ladicek

**Comment by edewit** [comment]
fixed in https://github.com/fabric8-launch/launchpad-addon/commit/db71e10b3a15f05078ef0f262afce1053b7ec722
